@url = http://localhost:3000/api

//AUTORES
GET {{url}}/autores

###

GET {{url}}/autores/2

###

POST {{url}}/autores
Content-Type: application/json

{
    "nombre":"Pepita",
    "email":"pepita@gmail.com",
    "imagen":"imagen1.com"
}

###

PUT {{url}}/autores/8
Content-Type: application/json

{
    "nombre": "Juan",
    "email":"juan@gmail.com",
    "imagen":"imagenjuan.jpg"
}

### 
DELETE {{url}}/autores/8

###

//POSTS

GET {{url}}/posts

###


GET {{url}}/posts/2

###

POST {{url}}/posts
Content-Type: application/json

{
    "titulo":"Cuentacuentos",
    "descripcion":"cuentos para dormir a cualquier niño",
    "categoria": "Arte",
    "autor_id":3

}



